apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-runner-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/stefan-raducan/k8s-tests.git
    targetRevision: develop
    path: argocd/envs/dev/test-cluster/github-runner
  destination:
    server: https://kubernetes.default.svc
    namespace: github-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
