apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.78.0 # Using a stable version of the chart
    helm:
      releaseName: opentelemetry-collector
      values: |
        mode: daemonset
        image:
          repository: otel/opentelemetry-collector-contrib
          tag: 0.91.0
        presets:
          kubernetesAttributes:
            enabled: true
          kubeletMetrics:
            enabled: true
          logsCollection:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: opentelemetry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
