apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Install after cert-manager (-2)
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-operator
    targetRevision: 0.44.0 # Using a specific stable version
    helm:
      releaseName: opentelemetry-operator
      values: |
        mode: daemonset

        image:
          repository: otel/opentelemetry-collector-k8s

        presets:
          # enables the k8sattributesprocessor and adds it to the traces, metrics, and logs pipelines
          kubernetesAttributes:
            enabled: true
          # enables the kubeletstatsreceiver and adds it to the metrics pipelines
          kubeletMetrics:
            enabled: true
          # Enables the filelogreceiver and adds it to the logs pipelines
          logsCollection:
            enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: opentelemetry-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
