apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-scaledjob-crd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kedacore/keda.git
    targetRevision: v2.16.0
    path: config/crd/bases
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
