apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Install after cert-manager (-2)
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: "0.141.1"
    helm:
      releaseName: opentelemetry-collector
      values: |
        mode: daemonset

        image:
          repository: otel/opentelemetry-collector-k8s

        presets:
          # enables the k8sattributesprocessor and adds it to the traces, metrics, and logs pipelines
          kubernetesAttributes:
            enabled: true
          # enables the kubeletstatsreceiver and adds it to the metrics pipelines
          kubeletMetrics:
            enabled: true
          logsCollection:
            enabled: true

        service:
          enabled: true
          type: ClusterIP

        config:
          exporters:
            otlp:
              endpoint: jaeger-collector.jaeger.svc.cluster.local:4317
              tls:
                insecure: true
          service:
            pipelines:
              traces:
                exporters: [otlp]
                processors: [k8sattributes, memory_limiter, batch]
                receivers: [otlp]

          ## If you want to send your data somewhere you need to
          ## configure an exporter, such as the otlp exporter
          # config:
          #   exporters:
          #     otlp:
          #       endpoint: "<SOME BACKEND>"
          #   service:
          #     pipelines:
          #       traces:
          #         exporters: [ otlp ]
          #       metrics:
          #         exporters: [ otlp ]
          #       logs:
          #         exporters: [ otlp ]

  destination:
    server: https://kubernetes.default.svc
    namespace: opentelemetry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
